### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class java.awt.image.BufferedImage

### ISSUE THREAD

**Issue by savvasdalkitsis** [rtyley/android-screenshot-lib#2]
It seems that the BufferedImage class doesn't exist on android. 

When we run the screenshot taking service, we get this exception:

Exception in thread "OnDemandScreenshotService logcat for c1607264611f030" java.lang.NoClassDefFoundError: Could not initialize class java.awt.image.BufferedImage
    at com.github.rtyley.android.screenshot.paparazzo.OnDemandScreenshotService.bufferedImageFrom(OnDemandScreenshotService.java:161)
    at com.github.rtyley.android.screenshot.paparazzo.OnDemandScreenshotService.takeScreenshotFor(OnDemandScreenshotService.java:126)
    at com.github.rtyley.android.screenshot.paparazzo.OnDemandScreenshotService.access$300(OnDemandScreenshotService.java:18)
    at com.github.rtyley.android.screenshot.paparazzo.OnDemandScreenshotService$ScreenshotRequestListener.processNewLines(OnDemandScreenshotService.java:107)
    at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:99)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:419)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:444)
    at com.github.rtyley.android.screenshot.paparazzo.OnDemandScreenshotService$LogCatCommandExecutor.run(OnDemandScreenshotService.java:71)
    at java.lang.Thread.run(Thread.java:680)

**Comment by rtyley** [comment]
Hi @savvasdalkitsis - the paparazzo code is only meant to run on your build system, not on the device - which means its running in a full, standard (Oracle/Sun) JVM, not the Dalvik VM.

Hope that helps!

review the 'How it works' section of the [documentation](https://github.com/rtyley/android-screenshot-lib/blob/master/README.markdown) for more detail:

## How it works

The system is in two parts, _paparazzo & celebrity_. Crucially, the paparazzo _only takes photos
when the celebrity asks_.
- _**paparazzo** - taking the photos_ : your desktop development environment runs an
  [OnDemandScreenshotService](https://github.com/rtyley/android-screenshot-lib/blob/master/paparazzo/src/main/java/com/github/rtyley/android/screenshot/paparazzo/OnDemandScreenshotService.java),
  using ddmlib to listen for log messages tagged with the special tag `screenshot_request`.
- _**celebrity** - the subject being photographed_ : your Android device runs your integration tests as it would normally, 
  just writing a `screenshot_request` log message whenever it wants a screenshot taken -  the _paparazzo_ service then 
  obliges by capturing an image from the device.
